name: Deploy Windows VM to GCP

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  PROJECT_ID: banded-pager-458723-h4
  REGION: us-central1
  INSTANCE_NAME: minecraft-server-windows

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}'
        
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ env.PROJECT_ID }}
        install_components: 'beta'

    - name: Deploy Windows VM
      run: |
        gcloud compute instances create ${{ env.INSTANCE_NAME }} \
          --project=${{ env.PROJECT_ID }} \
          --zone=${{ env.REGION }}-a \
          --machine-type=e2-micro \
          --image-family=windows-2022 \
          --image-project=windows-cloud \
          --boot-disk-size=50GB \
          --boot-disk-type=pd-balanced \
          --network=default \
          --subnet=default \
          --maintenance-policy=MIGRATE \
          --provisioning-model=STANDARD \
          --service-account=default \
          --no-shielded-secure-boot \
          --shielded-vtpm \
          --shielded-integrity-monitoring \
          --tags=http-server,https-server \
          --reservation-affinity=any
    - name: Create Firewall Rule for RDP
      run: |
        gcloud compute firewall-rules create allow-rdp \
          --direction=INGRESS \
          --priority=1000 \
          --network=default \
          --action=ALLOW \
          --rules=tcp:3389 \
          --source-ranges=0.0.0.0/0 \
          --target-tags=http-server || true

    - name: Get External IP
      run: |
        echo "External IP: $(gcloud compute instances describe ${{ env.INSTANCE_NAME }} --zone=${{ env.REGION }}-a --format='get(networkInterfaces[0].accessConfigs[0].natIP)')"
