name: golang-ci

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21' # or your project's Go version

      - name: Install golangci-lint
        run: |
          choco install golangci-lint -y
          golangci-lint --version

      - name: Run linter
        run: |
          golangci-lint run --timeout=2m