name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: make build 
      
  test:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: make build

    - name: Run unit tests
      run: make unit-test

    - name: Run integration tests
      run: make integration-test